/**
 * Field schema for the autonomous config form.
 *
 * Every field maps to a top-level key in the response from
 * GET /config/autonomous. `help` ties the parameter back to the steering
 * doc / log line / observable it gates. Nested blocks like
 * direction_aware_thresholds are surfaced as advanced YAML edits in the
 * Lab / Cycle tabs; this form covers the scalar parameters a CIO tunes
 * routinely.
 */

export type FieldType = 'int' | 'number' | 'bool' | 'string'

export interface FieldDef {
  key: string
  label: string
  section: string
  type: FieldType
  help: string
  gates?: string
  suffix?: string
  min?: number
  max?: number
  step?: number
}

export const AUTONOMOUS_SECTIONS = [
  'Core',
  'Cycle cadence',
  'Activation · Sharpe & Win rate',
  'Activation · Min trades',
  'Activation · Min return per trade',
  'Conviction',
  'Retirement',
  'Walk-forward',
  'Adaptive risk',
  'Performance feedback',
  'Directional balance',
  'Portfolio balance',
  'Drawdown sizing',
  'Conviction-tier sizing',
  'Vol scaling',
  'Rejection blacklist',
  'Regime dormancy',
  'Regime authority',
] as const

export const AUTONOMOUS_FIELDS: FieldDef[] = [
  // Core
  {
    key: 'enabled',
    label: 'Autonomous enabled',
    section: 'Core',
    type: 'bool',
    help: 'Master switch. When off, cycles do not run automatically — manual trigger only.',
    gates: 'cycle_history.log',
  },
  {
    key: 'proposal_count',
    label: 'Proposals per cycle',
    section: 'Core',
    type: 'int',
    help: 'Number of strategies the proposer attempts per cycle. Higher = broader exploration, slower cycle.',
    min: 10,
    max: 500,
  },
  {
    key: 'max_active_strategies',
    label: 'Max active strategies',
    section: 'Core',
    type: 'int',
    help: 'Hard cap on PAPER + LIVE count. When hit, new activations replace the worst current performer.',
    min: 5,
    max: 200,
  },
  {
    key: 'min_active_strategies',
    label: 'Min active strategies',
    section: 'Core',
    type: 'int',
    help: 'Floor below which we relax activation thresholds. Prevents the library ever being empty.',
    min: 1,
    max: 100,
  },
  {
    key: 'watchlist_size',
    label: 'Watchlist size',
    section: 'Core',
    type: 'int',
    help: 'Symbols per template watchlist. The scheduler rotates through this list.',
    min: 5,
    max: 50,
  },
  {
    key: 'backtested_ttl_cycles',
    label: 'BACKTESTED TTL (cycles)',
    section: 'Core',
    type: 'int',
    help: 'Stale BACKTESTED strategies are retired after this many cycles without activation.',
    min: 1,
    max: 200,
  },

  // Cycle cadence
  {
    key: 'signal_generation_interval',
    label: 'Signal gen interval',
    section: 'Cycle cadence',
    type: 'int',
    suffix: 's',
    help: 'Seconds between signal-generation passes. Default 1800 (30 min).',
    min: 60,
    max: 7200,
  },
  {
    key: 'dynamic_symbol_additions',
    label: 'Dynamic symbol additions',
    section: 'Cycle cadence',
    type: 'int',
    help: 'Symbols auto-added per cycle from the neglected-symbol pool (Phase 3 of _build_watchlists).',
    min: 0,
    max: 50,
  },
  {
    key: 'schedule_hour',
    label: 'Schedule hour (UTC)',
    section: 'Cycle cadence',
    type: 'int',
    help: 'Hour-of-day the weekly proposer runs.',
    min: 0,
    max: 23,
  },
  {
    key: 'schedule_minute',
    label: 'Schedule minute',
    section: 'Cycle cadence',
    type: 'int',
    help: 'Minute-of-hour for the weekly proposer.',
    min: 0,
    max: 59,
  },
  {
    key: 'schedule_day_of_week',
    label: 'Day of week',
    section: 'Cycle cadence',
    type: 'string',
    help: 'e.g. saturday · the day the weekly proposal runs.',
  },
  {
    key: 'signal_parallel_workers',
    label: 'Signal parallel workers',
    section: 'Cycle cadence',
    type: 'int',
    help: 'Worker threads that run signal generation concurrently.',
    min: 1,
    max: 16,
  },

  // Activation — Sharpe & WR
  {
    key: 'min_sharpe',
    label: 'Min Sharpe (default)',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    help: 'Walk-forward Sharpe gate for non-crypto/non-commodity strategies.',
    min: -2,
    max: 5,
    step: 0.05,
  },
  {
    key: 'min_sharpe_crypto',
    label: 'Min Sharpe (crypto)',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    help: 'Lower crypto Sharpe tolerance — crypto vol is higher so raw Sharpe is noisier.',
    min: -2,
    max: 5,
    step: 0.05,
  },
  {
    key: 'min_sharpe_commodity',
    label: 'Min Sharpe (commodity)',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    help: 'Commodity Sharpe gate — typically between stock and crypto.',
    min: -2,
    max: 5,
    step: 0.05,
  },
  {
    key: 'max_drawdown',
    label: 'Max drawdown (activation)',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    suffix: '%',
    help: 'Walk-forward max drawdown above which strategies are rejected at activation.',
    min: 5,
    max: 60,
    step: 0.5,
  },
  {
    key: 'min_win_rate',
    label: 'Min win rate',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    suffix: '%',
    help: 'Walk-forward win rate floor for default asset classes.',
    min: 20,
    max: 80,
    step: 0.5,
  },
  {
    key: 'min_win_rate_crypto',
    label: 'Min win rate (crypto)',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    suffix: '%',
    min: 10,
    max: 80,
    help: 'Crypto win-rate floor — lower because crypto strategies rely on tail expectancy.',
    step: 0.5,
  },
  {
    key: 'min_win_rate_commodity',
    label: 'Min win rate (commodity)',
    section: 'Activation · Sharpe & Win rate',
    type: 'number',
    suffix: '%',
    min: 10,
    max: 80,
    help: 'Commodity win-rate floor.',
    step: 0.5,
  },

  // Activation — Min trades
  {
    key: 'min_trades',
    label: 'Min trades (generic)',
    section: 'Activation · Min trades',
    type: 'int',
    help: 'Absolute minimum trade count in walk-forward window.',
    min: 1,
    max: 50,
  },
  {
    key: 'min_trades_dsl',
    label: 'Min trades (DSL, 1d)',
    section: 'Activation · Min trades',
    type: 'int',
    help: 'Daily DSL strategies — ensures WF Sharpe is statistically meaningful.',
    min: 1,
    max: 50,
  },
  {
    key: 'min_trades_dsl_4h',
    label: 'Min trades (DSL, 4h)',
    section: 'Activation · Min trades',
    type: 'int',
    help: '4H DSL strategies.',
    min: 1,
    max: 50,
  },
  {
    key: 'min_trades_dsl_1h',
    label: 'Min trades (DSL, 1h)',
    section: 'Activation · Min trades',
    type: 'int',
    help: '1H DSL strategies — higher floor because 1h Sharpe annualises faster.',
    min: 5,
    max: 100,
  },
  {
    key: 'min_trades_alpha_edge',
    label: 'Min trades (Alpha Edge)',
    section: 'Activation · Min trades',
    type: 'int',
    help: 'Alpha Edge fundamental-signal templates.',
    min: 1,
    max: 50,
  },
  {
    key: 'min_trades_crypto_1d',
    label: 'Min trades (crypto, 1d)',
    section: 'Activation · Min trades',
    type: 'int',
    min: 1,
    max: 50,
    help: 'Crypto daily — lower because crypto samples are thin.',
  },
  {
    key: 'min_trades_crypto_4h',
    label: 'Min trades (crypto, 4h)',
    section: 'Activation · Min trades',
    type: 'int',
    min: 1,
    max: 50,
    help: 'Crypto 4h.',
  },
  {
    key: 'min_trades_crypto_1h',
    label: 'Min trades (crypto, 1h)',
    section: 'Activation · Min trades',
    type: 'int',
    min: 1,
    max: 100,
    help: 'Crypto 1h.',
  },
  {
    key: 'min_trades_commodity',
    label: 'Min trades (commodity)',
    section: 'Activation · Min trades',
    type: 'int',
    min: 1,
    max: 50,
    help: 'Commodity — often fewer trades per WF window.',
  },

  // Activation — Min RPT
  ...(
    [
      ['min_rpt_stock', 'Stock', ''],
      ['min_rpt_stock_4h', 'Stock 4h', ''],
      ['min_rpt_stock_1h', 'Stock 1h', ''],
      ['min_rpt_etf', 'ETF', ''],
      ['min_rpt_etf_4h', 'ETF 4h', ''],
      ['min_rpt_etf_1h', 'ETF 1h', ''],
      ['min_rpt_forex', 'Forex', ''],
      ['min_rpt_forex_1h', 'Forex 1h', ''],
      ['min_rpt_crypto', 'Crypto', ''],
      ['min_rpt_crypto_1d', 'Crypto 1d', ''],
      ['min_rpt_crypto_4h', 'Crypto 4h', ''],
      ['min_rpt_crypto_1h', 'Crypto 1h', ''],
      ['min_rpt_index', 'Index', ''],
      ['min_rpt_index_1h', 'Index 1h', ''],
      ['min_rpt_commodity', 'Commodity', ''],
      ['min_rpt_commodity_4h', 'Commodity 4h', ''],
    ] as const
  ).map(
    ([key, label]) =>
      ({
        key,
        label,
        section: 'Activation · Min return per trade',
        type: 'number',
        suffix: '%',
        step: 0.01,
        min: 0,
        max: 25,
        help: `Minimum average return per trade for ${label.toLowerCase()} to clear activation.`,
      }) as FieldDef,
  ),

  // Conviction
  {
    key: 'conviction_threshold',
    label: 'Conviction threshold (equity)',
    section: 'Conviction',
    type: 'int',
    help: 'DEMO conviction floor for equity. Live has its own separate threshold on the Live Trading tab.',
    min: 40,
    max: 100,
    gates: 'conviction_scorer.score_strategy',
  },
  {
    key: 'conviction_threshold_crypto',
    label: 'Conviction threshold (crypto)',
    section: 'Conviction',
    type: 'int',
    help: 'DEMO conviction floor for crypto — typically lower than equity per steering doc.',
    min: 40,
    max: 100,
  },

  // Retirement
  {
    key: 'retirement_max_sharpe',
    label: 'Retirement · max Sharpe',
    section: 'Retirement',
    type: 'number',
    step: 0.05,
    min: -3,
    max: 2,
    help: 'Live Sharpe at or below this starts the retirement countdown.',
  },
  {
    key: 'retirement_max_drawdown',
    label: 'Retirement · max DD',
    section: 'Retirement',
    type: 'number',
    suffix: '%',
    min: 5,
    max: 60,
    step: 0.5,
    help: 'Live DD above this starts retirement.',
  },
  {
    key: 'retirement_min_win_rate',
    label: 'Retirement · min WR',
    section: 'Retirement',
    type: 'number',
    suffix: '%',
    min: 10,
    max: 60,
    step: 0.5,
    help: 'Live WR below this starts retirement.',
  },
  {
    key: 'retirement_min_trades_for_evaluation',
    label: 'Retirement · min trades',
    section: 'Retirement',
    type: 'int',
    min: 1,
    max: 100,
    help: 'Trades below which we skip evaluation — avoids retiring on a single bad sequence.',
  },
  {
    key: 'retirement_min_live_trades',
    label: 'Retirement · min live trades',
    section: 'Retirement',
    type: 'int',
    min: 1,
    max: 50,
    help: 'Live-only trade floor before retirement evaluation kicks in.',
  },
  {
    key: 'retirement_rolling_window_days',
    label: 'Retirement · rolling window',
    section: 'Retirement',
    type: 'int',
    suffix: 'd',
    min: 7,
    max: 365,
    help: 'Window over which retirement criteria are evaluated.',
  },
  {
    key: 'retirement_consecutive_failures',
    label: 'Retirement · consecutive fails',
    section: 'Retirement',
    type: 'int',
    min: 1,
    max: 10,
    help: 'Number of consecutive criteria breaches before retirement fires.',
  },
  {
    key: 'retirement_probation_days',
    label: 'Retirement · probation',
    section: 'Retirement',
    type: 'int',
    suffix: 'd',
    min: 1,
    max: 180,
    help: 'Grace period before retirement becomes eligible.',
  },

  // Walk-forward
  {
    key: 'wf_train_days',
    label: 'WF train days',
    section: 'Walk-forward',
    type: 'int',
    suffix: 'd',
    min: 30,
    max: 1825,
    help: 'In-sample training window.',
  },
  {
    key: 'wf_test_days',
    label: 'WF test days',
    section: 'Walk-forward',
    type: 'int',
    suffix: 'd',
    min: 14,
    max: 730,
    help: 'Out-of-sample validation window.',
  },

  // Adaptive risk
  {
    key: 'adaptive_risk_enabled',
    label: 'Adaptive risk enabled',
    section: 'Adaptive risk',
    type: 'bool',
    help: 'Allow SL/TP to adapt per-signal within the bounds below.',
  },
  {
    key: 'adaptive_min_sl_pct',
    label: 'Min SL',
    section: 'Adaptive risk',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 50,
    step: 0.1,
    help: 'Floor on adaptive stop-loss distance.',
  },
  {
    key: 'adaptive_max_sl_pct',
    label: 'Max SL',
    section: 'Adaptive risk',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 50,
    step: 0.1,
    help: 'Ceiling on adaptive stop-loss.',
  },
  {
    key: 'adaptive_min_tp_pct',
    label: 'Min TP',
    section: 'Adaptive risk',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    step: 0.1,
    help: 'Floor on adaptive take-profit distance.',
  },
  {
    key: 'adaptive_max_tp_pct',
    label: 'Max TP',
    section: 'Adaptive risk',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    step: 0.1,
    help: 'Ceiling on adaptive take-profit.',
  },
  {
    key: 'adaptive_min_rr_ratio',
    label: 'Min R:R',
    section: 'Adaptive risk',
    type: 'number',
    min: 0.5,
    max: 10,
    step: 0.05,
    help: 'Minimum reward:risk ratio for an adaptive setup to pass.',
  },

  // Performance feedback
  {
    key: 'feedback_lookback_days',
    label: 'Feedback lookback',
    section: 'Performance feedback',
    type: 'int',
    suffix: 'd',
    min: 14,
    max: 365,
    help: 'Window over which proposer feedback scores are computed.',
  },
  {
    key: 'feedback_min_trades',
    label: 'Feedback min trades',
    section: 'Performance feedback',
    type: 'int',
    min: 1,
    max: 50,
    help: 'Symbol must have this many trades before feedback downweights it.',
  },
  {
    key: 'feedback_max_weight',
    label: 'Feedback max weight',
    section: 'Performance feedback',
    type: 'number',
    min: 1,
    max: 5,
    step: 0.05,
    help: 'Upper bound on feedback weight amplification.',
  },
  {
    key: 'feedback_min_weight',
    label: 'Feedback min weight',
    section: 'Performance feedback',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.05,
    help: 'Lower bound on feedback weight — 0 completely blacklists a symbol.',
  },
  {
    key: 'feedback_weight_decay_per_day',
    label: 'Feedback decay',
    section: 'Performance feedback',
    type: 'number',
    min: 0,
    max: 0.2,
    step: 0.001,
    help: 'Daily exponential decay — old trades matter less.',
  },

  // Directional balance
  {
    key: 'directional_balance_enabled',
    label: 'Directional balance enabled',
    section: 'Directional balance',
    type: 'bool',
    help: 'Enforce long/short balance across the portfolio.',
  },
  {
    key: 'directional_min_long_pct',
    label: 'Min long %',
    section: 'Directional balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Floor on long-side exposure.',
  },
  {
    key: 'directional_max_long_pct',
    label: 'Max long %',
    section: 'Directional balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Ceiling on long-side exposure.',
  },
  {
    key: 'directional_min_short_pct',
    label: 'Min short %',
    section: 'Directional balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Floor on short-side exposure.',
  },
  {
    key: 'directional_max_short_pct',
    label: 'Max short %',
    section: 'Directional balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Ceiling on short-side exposure.',
  },

  // Portfolio balance
  {
    key: 'max_long_exposure_pct',
    label: 'Max long exposure',
    section: 'Portfolio balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 200,
    help: 'Hard cap on aggregate long exposure.',
  },
  {
    key: 'max_short_exposure_pct',
    label: 'Max short exposure',
    section: 'Portfolio balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 200,
    help: 'Hard cap on aggregate short exposure.',
  },
  {
    key: 'max_sector_exposure_pct',
    label: 'Max sector exposure',
    section: 'Portfolio balance',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Soft cap on any single sector — proposer biases away above this level.',
  },

  // Drawdown sizing
  {
    key: 'drawdown_sizing_enabled',
    label: 'Drawdown sizing enabled',
    section: 'Drawdown sizing',
    type: 'bool',
    help: 'Shrink position sizes when portfolio is in drawdown.',
  },
  {
    key: 'drawdown_sizing_threshold_5pct',
    label: 'Size @ 5% DD',
    section: 'Drawdown sizing',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Sizing factor applied when 30d peak-to-trough DD exceeds 5%.',
  },
  {
    key: 'drawdown_sizing_threshold_10pct',
    label: 'Size @ 10% DD',
    section: 'Drawdown sizing',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 100,
    help: 'Sizing factor applied above 10% DD.',
  },
  {
    key: 'drawdown_sizing_lookback_days',
    label: 'DD lookback',
    section: 'Drawdown sizing',
    type: 'int',
    suffix: 'd',
    min: 7,
    max: 120,
    help: 'Rolling window for peak calculation.',
  },

  // Conviction-tier sizing
  {
    key: 'conviction_tier_enabled',
    label: 'Conviction-tier sizing',
    section: 'Conviction-tier sizing',
    type: 'bool',
    help: 'Upsize positions for high-conviction setups.',
  },
  {
    key: 'conviction_tier_multiplier_75',
    label: '×75 tier multiplier',
    section: 'Conviction-tier sizing',
    type: 'number',
    min: 1,
    max: 3,
    step: 0.05,
    help: 'Size multiplier when conviction score ≥ 75.',
  },
  {
    key: 'conviction_tier_multiplier_80',
    label: '×80 tier multiplier',
    section: 'Conviction-tier sizing',
    type: 'number',
    min: 1,
    max: 3,
    step: 0.05,
    help: 'Size multiplier when conviction score ≥ 80.',
  },

  // Vol scaling
  {
    key: 'vol_scaling_min_scale',
    label: 'Min vol scale',
    section: 'Vol scaling',
    type: 'number',
    min: 0,
    max: 2,
    step: 0.05,
    help: 'Floor on vol-based size multiplier.',
  },
  {
    key: 'vol_scaling_max_scale',
    label: 'Max vol scale',
    section: 'Vol scaling',
    type: 'number',
    min: 0.5,
    max: 3,
    step: 0.05,
    help: 'Ceiling on vol-based size multiplier.',
  },
  {
    key: 'vol_scaling_max_symbol_pct',
    label: 'Max per-symbol %',
    section: 'Vol scaling',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 20,
    step: 0.1,
    help: 'Hard cap on any single symbol as % of equity.',
  },
  {
    key: 'vol_scaling_sector_soft_cap_pct',
    label: 'Sector soft cap',
    section: 'Vol scaling',
    type: 'number',
    suffix: '%',
    min: 0,
    max: 80,
    step: 0.5,
    help: 'Soft cap per sector — proposer deprioritises above this.',
  },

  // Rejection blacklist
  {
    key: 'rejection_blacklist_threshold',
    label: 'Rejection threshold',
    section: 'Rejection blacklist',
    type: 'int',
    min: 1,
    max: 20,
    help: 'Consecutive rejections before a (template, symbol) hits the blacklist.',
  },
  {
    key: 'rejection_blacklist_cooldown_days',
    label: 'Rejection cooldown',
    section: 'Rejection blacklist',
    type: 'int',
    suffix: 'd',
    min: 1,
    max: 365,
    help: 'Days on the blacklist before re-evaluation — regime changes can shorten this early.',
  },

  // Regime dormancy (sleep/wake regime-mismatched validated strategies)
  {
    key: 'regime_dormancy_enabled',
    label: 'Regime dormancy',
    section: 'Regime dormancy',
    type: 'bool',
    help: 'Sleep regime-mismatched-but-validated strategies (kept, no signals) and wake them when their regime returns — instead of retiring + deleting. Never touches LIVE. KEEP OFF until the regime-flip backtest validates it (design §7).',
    gates: 'RegimeDormancy logs / Library "Dormant" filter',
  },
  {
    key: 'regime_dormancy_sleep_confirm_days',
    label: 'Sleep confirm days',
    section: 'Regime dormancy',
    type: 'int',
    suffix: 'd',
    min: 1,
    max: 30,
    help: 'Regime must be stable ≥ this many days before a mismatched strategy is put to sleep (anti-flap).',
  },
  {
    key: 'regime_dormancy_wake_confirm_days',
    label: 'Wake confirm days',
    section: 'Regime dormancy',
    type: 'int',
    suffix: 'd',
    min: 1,
    max: 30,
    help: 'Regime must be stable ≥ this many days before a dormant strategy is woken.',
  },
  {
    key: 'regime_dormancy_min_dwell_days',
    label: 'Min dwell days',
    section: 'Regime dormancy',
    type: 'int',
    suffix: 'd',
    min: 0,
    max: 30,
    help: 'Minimum time in a state before toggling again — prevents oscillation at a regime boundary.',
  },
  {
    key: 'regime_dormancy_max_warm_age_days',
    label: 'Max warm age',
    section: 'Regime dormancy',
    type: 'int',
    suffix: 'd',
    min: 7,
    max: 365,
    help: 'A dormant strategy older than this is flagged for re-validation when woken (its edge may have drifted).',
  },
  {
    key: 'regime_dormancy_max_dormant_days',
    label: 'Max dormant age (bench expiry)',
    section: 'Regime dormancy',
    type: 'int',
    suffix: 'd',
    min: 7,
    max: 730,
    help: 'A strategy dormant longer than this WITHOUT its regime recurring is retired (bench expiry) — its validation is stale and re-proposing fresh beats keeping it warm. Default 90.',
  },

  // Regime authority (debounce of the raw sub-regime classifier)
  {
    key: 'regime_authority_confirm_days',
    label: 'Confirm days',
    section: 'Regime authority',
    type: 'int',
    suffix: 'd',
    min: 1,
    max: 30,
    help: 'A new raw sub-regime must persist this many consecutive trading days before it becomes the official regime the system acts on. Debounces the raw classifier (which flips every ~1-2 days). Tuned: 5 → ~13 confirmed changes/yr, ~3.4-week median dwell; 7 → ~8/yr, ~4-week.',
    gates: 'RegimeAuthority logs / regime_history confirmed changes',
  },
]
